CREATE DATABASE IF NOT EXISTS example;
CREATE DATABASE IF NOT EXISTS sample;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255)
);
INSERT INTO users (name) VALUES ('Eugene')
